#####INTERNAL TESTING#####
setwd("[path to your working directory]")
sink("output.R.txt", split=TRUE)
print("#####Testing#####")
print("#data process")
data_bin_train<-read.csv("training.csv", head=TRUE)
names(data_bin_train)
data_bin_test<-read.csv("test.csv", head=TRUE)
names(data_bin_test)
dspt_bin_train<-subset(data_bin_train,select=c(-Deamidation))
dspt_bin_test<-subset(data_bin_test,select=c(-Deamidation))
class_bin_train<-subset(data_bin_train, select=c(Deamidation))
class_bin_test<-subset(data_bin_test, select=c(Deamidation))

print("#SVM_bin")

print("#via caret-kerlab_svm Radial Kernel")
library("caret")
library("ROCR")
library("pROC")
fitControl <- trainControl(method = "CV",number = 10,returnResamp = "all", verboseIter = FALSE, classProbs = TRUE)
set.seed(2)
caret_svm_bin_rk_cv10 <- train(Deamidation~., data=data_bin_train, method = "svmRadial", preProcess = c("center", "scale"), tuneLength = 10, trControl = fitControl)
caret_svm_bin_rk_cv10
varImp(caret_svm_bin_rk_cv10)
svm_bin_Preds <- extractPrediction(list(caret_svm_bin_rk_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
print("#SVM binary prediction analysis")
svm_bin_Preds_test<-svm_bin_Preds[svm_bin_Preds$dataType == "Test", ]
confusionMatrix(svm_bin_Preds_test$pred, svm_bin_Preds_test$obs)
svm_bin_Probs <- extractProb(list(caret_svm_bin_rk_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
svm_bin_Probs_test<-svm_bin_Probs[svm_bin_Probs$dataType == "Test", ]
caret_svm_roc <- prediction(svm_bin_Probs_test$No,class_bin_test)
print("#Area under curve (AUC) value of ROC plot")
performance(caret_svm_roc, 'auc')
caret_svm_perf <- performance(caret_svm_roc, 'tpr', 'fpr')
print("#A ROC plot is output to caret_svm_bin_rk_roc.png and svm_roc.csv")
svm_roc<-data.frame(caret_svm_perf@x.values, caret_svm_perf@y.values)
colnames(svm_roc) <- c("False positive rate", "True positive rate")
write.table(svm_roc, file = "svm_roc.csv", sep = ",", row.names = FALSE )
png("caret_svm_bin_rk_roc.png")
plot(caret_svm_perf)
dev.off()

library("randomForest")
print("#Random Forest binary class via caret (randomForest)")
caret_rf_bin_randomf_cv10 <- train(Deamidation~., data=data_bin_train, method = "rf", preProcess = c("center", "scale"), tuneLength = 10, trControl = fitControl)
caret_rf_bin_randomf_cv10
varImp(caret_rf_bin_randomf_cv10)
rf_bin_Preds <- extractPrediction(list(caret_rf_bin_randomf_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
print("#Random Forest binary prediction analysis")
rf_bin_Preds_test<-rf_bin_Preds[rf_bin_Preds$dataType == "Test", ]
confusionMatrix(rf_bin_Preds_test$pred, rf_bin_Preds_test$obs)
rf_bin_Probs <- extractProb(list(caret_rf_bin_randomf_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
rf_bin_Probs_test<-rf_bin_Probs[rf_bin_Probs$dataType == "Test", ]
caret_rf_roc <- prediction(rf_bin_Probs_test$No,class_bin_test)
print("#Area under curve (AUC) value of ROC plot")
performance(caret_rf_roc, 'auc')
caret_rf_perf <- performance(caret_rf_roc, 'tpr', 'fpr')
print("#A ROC plot is output to caret_rf_bin_roc.png and rf_roc.csv")
rf_roc<-data.frame(caret_rf_perf@x.values, caret_rf_perf@y.values)
colnames(rf_roc) <- c("False positive rate", "True positive rate")
write.table(rf_roc, file = "rf_roc.csv", sep = ",", row.names = FALSE )
png("caret_rf_bin_roc.png")
plot(caret_rf_perf)
dev.off()

print("#Naive BaNoian binary class via caret(klaR)")
#library("klaR")
caret_nb_bin_klaR_cv10 <- train(Deamidation~., data=data_bin_train, method = "nb", preProcess = c("center", "scale"), tuneLength = 10, trControl = fitControl)
caret_nb_bin_klaR_cv10
varImp(caret_nb_bin_klaR_cv10)
nb_bin_Preds <- extractPrediction(list(caret_nb_bin_klaR_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
print("#Naive BaNoian binary prediction analysis")
nb_bin_Preds_test<-nb_bin_Preds[nb_bin_Preds$dataType == "Test", ]
confusionMatrix(nb_bin_Preds_test$pred, nb_bin_Preds_test$obs)
nb_bin_Probs <- extractProb(list(caret_nb_bin_klaR_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
nb_bin_Probs_test<-nb_bin_Probs[nb_bin_Probs$dataType == "Test", ]
caret_nb_roc <- prediction(nb_bin_Probs_test$No,class_bin_test)
print("#Area under curve (AUC) value of ROC plot")
performance(caret_nb_roc, 'auc')
caret_nb_perf <- performance(caret_nb_roc, 'tpr', 'fpr')
print("#A ROC plot is output to caret_nb_bin_roc.png and nb_roc.csv")
nb_roc<-data.frame(caret_nb_perf@x.values, caret_nb_perf@y.values)
colnames(nb_roc) <- c("False positive rate", "True positive rate")
write.table(nb_roc, file = "nb_roc.csv", sep = ",", row.names = FALSE )
png("caret_nb_bin_roc.png")
plot(caret_nb_perf)
dev.off()

#library("knn")
print("#K nearest neighbor binary class via caret")
caret_knn_bin_cv10 <- train(Deamidation~., data=data_bin_train, method = "knn", preProcess = c("center", "scale"), tuneLength = 10, trControl = fitControl)
caret_knn_bin_cv10
varImp(caret_knn_bin_cv10)
knn_bin_Preds <- extractPrediction(list(caret_knn_bin_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
print("#K nearest neighbor binary prediction analysis")
knn_bin_Preds_test<-knn_bin_Preds[knn_bin_Preds$dataType == "Test", ]
confusionMatrix(knn_bin_Preds_test$pred, knn_bin_Preds_test$obs)
knn_bin_Probs <- extractProb(list(caret_knn_bin_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
knn_bin_Probs_test<-knn_bin_Probs[knn_bin_Probs$dataType == "Test", ]
caret_knn_roc <- prediction(knn_bin_Probs_test$No,class_bin_test)
print("#Area under curve (AUC) value of ROC plot")
performance(caret_knn_roc, 'auc')
caret_knn_perf <- performance(caret_knn_roc, 'tpr', 'fpr')
print("#A ROC plot is output to caret_knn_bin_roc.png and knn_roc.csv")
knn_roc<-data.frame(caret_knn_perf@x.values, caret_knn_perf@y.values)
colnames(knn_roc) <- c("False positive rate", "True positive rate")
write.table(knn_roc, file = "knn_roc.csv", sep = ",", row.names = FALSE )
png("caret_knn_bin_roc.png")
plot(caret_knn_perf)
dev.off()

print("#Neural Net binary class via caret (nnet)")
caret_ann_bin_nnet_cv10 <- train(Deamidation~., data=data_bin_train, method = "nnet", trace=FALSE, preProcess = c("center", "scale"), tuneLength = 10, trControl = fitControl)
caret_ann_bin_nnet_cv10
varImp(caret_ann_bin_nnet_cv10)
ann_bin_Preds <- extractPrediction(list(caret_ann_bin_nnet_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
print("#Neural Net binary prediction analysis")
ann_bin_Preds_test<-ann_bin_Preds[ann_bin_Preds$dataType == "Test", ]
confusionMatrix(ann_bin_Preds_test$pred, ann_bin_Preds_test$obs)
ann_bin_Probs <- extractProb(list(caret_ann_bin_nnet_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
ann_bin_Probs_test<-ann_bin_Probs[ann_bin_Probs$dataType == "Test", ]
caret_ann_roc <- prediction(ann_bin_Probs_test$No,class_bin_test)
print("#Area under curve (AUC) value of ROC plot")
performance(caret_ann_roc, 'auc')
caret_ann_perf <- performance(caret_ann_roc, 'tpr', 'fpr')
print("#A ROC plot is output to caret_ann_bin_roc.png and ann_roc.csv")
ann_roc<-data.frame(caret_ann_perf@x.values, caret_ann_perf@y.values)
colnames(ann_roc) <- c("False positive rate", "True positive rate")
write.table(ann_roc, file = "ann_roc.csv", sep = ",", row.names = FALSE )
png("caret_ann_bin_roc.png")
plot(caret_ann_perf)
dev.off()

print("#Partial least square binary class via caret(pls)")
library("pls")
caret_pls_bin_pls_cv10 <- train(Deamidation~., data=data_bin_train, method = "pls", preProcess = c("center", "scale"), tuneLength = 10, trControl = fitControl)
caret_pls_bin_pls_cv10
varImp(caret_pls_bin_pls_cv10)
pls_bin_Preds <- extractPrediction(list(caret_pls_bin_pls_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
print("#Partial least square binary prediction analysis")
pls_bin_Preds_test<-pls_bin_Preds[pls_bin_Preds$dataType == "Test", ]
confusionMatrix(pls_bin_Preds_test$pred, pls_bin_Preds_test$obs)
pls_bin_Probs <- extractProb(list(caret_pls_bin_pls_cv10),testX=dspt_bin_test[,1:13], testY=class_bin_test[,1])
pls_bin_Probs_test<-pls_bin_Probs[pls_bin_Probs$dataType == "Test", ]
caret_pls_roc <- prediction(pls_bin_Probs_test$No,class_bin_test)
print("#Area under curve (AUC) value of ROC plot")
performance(caret_pls_roc, 'auc')
caret_pls_perf <- performance(caret_pls_roc, 'tpr', 'fpr')
print("#A ROC plot is output to caret_pls_bin_roc.png and pls_roc.csv")
pls_roc<-data.frame(caret_pls_perf@x.values, caret_pls_perf@y.values)
colnames(pls_roc) <- c("False positive rate", "True positive rate")
write.table(pls_roc, file = "pls_roc.csv", sep = ",", row.names = FALSE )
png("caret_pls_bin_roc.png")
plot(caret_pls_perf)
dev.off()

sink()
close(file("output.R.txt"))
